### ISSUE TITLE
대표 사진 값은 필수입니다.

### ISSUE THREAD

**Issue by eondcom** [hellojo011/marketplace_XE#1]
XE1.11.1입니다.
xe 최신버전에서 썸네일 파일 업로드가 제대로 되지 않는 거 같습니다.
js 부분이 문제인줄 알고 봤더니 아예 js에서는 업로드 부분이 없네요.
마켓플레이스 모듈 php단 수정이 필요해보입니다. 
직접 능력은 안되서 그냥 이슈만 남겨봅니다.^^;

**Comment by hellojo011** [comment]
XE 1.11.1 설치후 테스트해봤습니다.

썸네일 4개를 전부 다 채우거나 폼에서 지워버려야만 업로드되는 걸 봐선 업로드측 문제는 맞는 거 같은데 저도 포크해서 Rhymix 1.9.8.1에서 돌아가도록만 수정한지라 업로드측이 어딘지 찾기가 어렵네요... 노력은 해보겠습니다.

**Comment by hellojo011** [comment]
일단 야매로는 해결해보았습니다. 업로드부분은 찾았으니 기존 소스 보고 어디가 오작동하는지 확인해봐야겠네요.
